version: '3.8'

services:
  # MongoDB with replica set
  mongodb:
    image: mongo:7.0
    container_name: clinic_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: clinic_db
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/opt/keyfile"]
    networks:
      - clinic_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://admin:password123@mongodb:27017/clinic_db?authSource=admin&replicaSet=rs0
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-change-in-production
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - clinic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: clinic_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - clinic_network

volumes:
  mongodb_data:
    driver: local

networks:
  clinic_network:
    driver: bridge
